import { Test, TestingModule } from "@nestjs/testing";
import { UsersService } from "./users.service";
import { PrismaService } from "../prisma/prisma.service";
import { User, Prisma, VerificationStatus } from "@prisma/client";

// Define the shape of the mock service with explicit Jest mock types
interface MockPrismaClient {
  user: {
    create: jest.Mock<Promise<User>, [Prisma.UserCreateArgs]>;
  };
}

const mockPrismaService: MockPrismaClient = {
  user: {
    create: jest.fn<Promise<User>, [Prisma.UserCreateArgs]>(),
  },
};

describe("UsersService", () => {
  let service: UsersService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UsersService,
        {
          provide: PrismaService,
          useValue: mockPrismaService,
        },
      ],
    }).compile();

    service = module.get<UsersService>(UsersService);
  });

  it("should be defined", () => {
    expect(service).toBeDefined();
  });

  it("should hash password on create", async () => {
    const createUserDto = {
      email: "test@example.com",
      password: "plainpassword",
      firstName: "Test",
      lastName: "User",
      birthDate: "1990-01-01",
      gender: "male",
    };

    // The mock data needs to match the User type exactly
    // We remove fields that are relations (photos, interests, media) as they are not on the User type directly
    // but rather are relation properties. However, findUnique/create returns User type which DOES NOT have these
    // unless included. But TypeScript User type usually only has scalar fields.
    // Wait, the error said: 'photos' does not exist in type ...
    // This confirms 'photos' is NOT in the User type generated by Prisma.
    // It is likely a relation.

    mockPrismaService.user.create.mockResolvedValue({
      id: 1,
      email: createUserDto.email,
      emailVerified: null,
      phoneNumber: null,
      phoneVerified: null,
      verificationStatus: VerificationStatus.UNVERIFIED,

      firstName: createUserDto.firstName,
      lastName: createUserDto.lastName,
      patronymic: null,
      birthDate: new Date(createUserDto.birthDate),
      gender: "MALE", // Using generic string here, or should match enum
      nationality: null,
      language: "ru",

      latitude: null,
      longitude: null,

      role: "USER",
      isBanned: false,
      messagingBlocked: false,
      callEnabled: false,

      createdAt: new Date(),
      updatedAt: new Date(),
      lastLoginAt: null,
      lastActiveAt: null,

      bio: null,
      avatarUrl: null,
      height: null,
      education: null,
      jobTitle: null,
      company: null,
      smoking: null,
      drinking: null,
      zodiac: null,

      lookingFor: [],
      genderPreference: null,

      password: "hashedpassword",

      searchRadius: 100,
      isGlobalSearch: false,
      ageMinPreference: 18,
      ageMaxPreference: 100,

      isPassportActive: false,
      passportLat: null,
      passportLon: null,

      subscriptionTier: "FREE",
      subscriptionExpiresAt: null,
    } as unknown as User);

    await service.create(createUserDto);

    const expectedDataMatcher = expect.objectContaining({
      email: "test@example.com",
    }) as unknown;

    const expectedArgMatcher = expect.objectContaining({
      data: expectedDataMatcher,
    }) as unknown;

    expect(mockPrismaService.user.create).toHaveBeenCalledWith(
      expectedArgMatcher,
    );

    const createCallArgs = mockPrismaService.user.create.mock.calls[0][0];

    const data = createCallArgs.data;
    if (data && "password" in data) {
      expect(data.password).not.toBe("plainpassword");
    } else {
      throw new Error("Data or password missing in call args");
    }
  });
});
